#开发环境
development:
  database:
    host: 127.0.0.1
    user: root
    pwd: 123456
    port: 3306
    #数据库名称
    db_name: test
    #数据库表名称
    table_name: customer
    #DriverName
    driver_name: mysql
